import type {
  SectionReview,
  SpaceRequestRecord,
  WorkforceMonthData,
} from './spaceRequestFormTypes';

const NO_WORKFORCE_DATA: WorkforceMonthData = {
  counts: {},
};

function sectionReview(
  status: SectionReview['status'],
  comment = ''
): SectionReview {
  return { status, comment, attachments: [] };
}

export const SPACE_REQUEST_MOCK_DATA: SpaceRequestRecord[] = [
  {
    id: 'SRF-0031',
    srfNumber: '0031',
    dateRaised: '27/05/2025',
    teamcenterNumber: '101555014',
    revision: '001',
    title: 'HEA/HTR Construction Works',
    originatorCompanyName: 'Clancy',
    projectContractRefNumber: 'ADW000-042',
    mobilisationDate: '22/08/2025',
    demobilisationDate: '31/12/2026',
    plotFootprint: 'HTR Boundary 60mx60m, lay down area 60mx60m = 7,667 M2',
    developmentSiteType: 'MDS',
    mainDevelopmentSiteArea: '(TCA) West',
    siteZone: 'Zone 8',
    requestTypeMds: 'Work Area & Welfare',
    laydownWarehousePort: 'N/A (MDS)',
    areaOsi: 'N/A (MDS)',
    requestTypeOsi: 'N/A (MDS)',
    status: 'Submitted',
    modules: {
      workArea: true,
      it: false,
      water: true,
      welfare: true,
      power: true,
      workforce: true,
    },
    workforceData: {
      counts: {
        '2025-08': 60,
        '2025-09': 60,
        '2025-10': 60,
        '2025-11': 60,
        '2025-12': 60,
        '2026-01': 75,
        '2026-02': 75,
        '2026-03': 75,
        '2026-04': 75,
        '2026-05': 75,
        '2026-06': 75,
        '2026-07': 90,
        '2026-08': 90,
        '2026-09': 90,
        '2026-10': 90,
        '2026-11': 90,
        '2026-12': 90,
      },
    },
    sectionReviews: {
      general: sectionReview('Under Review'),
      'work-area': sectionReview('Under Review'),
      water: sectionReview('Under Review'),
      welfare: sectionReview('Under Review'),
      power: sectionReview('Under Review'),
      workforce: sectionReview('Under Review'),
    },
  },
  {
    id: 'SRF-0032',
    srfNumber: '0032',
    dateRaised: '03/06/2025',
    teamcenterNumber: '101555091',
    revision: '002',
    title: 'Site Compound Welfare Setup',
    originatorCompanyName: 'Balfour Beatty',
    projectContractRefNumber: 'ADW000-118',
    mobilisationDate: '02/09/2025',
    demobilisationDate: '15/01/2027',
    plotFootprint: 'Compound area 40mx50m = 2,000 M2',
    developmentSiteType: 'MDS',
    mainDevelopmentSiteArea: '(TCA) East',
    siteZone: 'Zone 3',
    requestTypeMds: 'Welfare & IT',
    laydownWarehousePort: 'N/A (MDS)',
    areaOsi: 'N/A (MDS)',
    requestTypeOsi: 'N/A (MDS)',
    status: 'Approved',
    modules: {
      workArea: true,
      it: true,
      water: false,
      welfare: true,
      power: false,
      workforce: true,
    },
    workforceData: {
      counts: {
        '2025-09': 40,
        '2025-10': 40,
        '2025-11': 40,
        '2025-12': 40,
        '2026-01': 40,
        '2026-02': 40,
        '2026-03': 55,
        '2026-04': 55,
        '2026-05': 55,
        '2026-06': 55,
        '2026-07': 55,
        '2026-08': 55,
        '2026-09': 65,
        '2026-10': 65,
        '2026-11': 65,
        '2026-12': 65,
        '2027-01': 65,
      },
    },
    sectionReviews: {
      general: sectionReview(
        'Approved',
        'Layout and welfare capacity match the site plan on file. Approved as submitted.'
      ),
      'work-area': sectionReview('Approved', 'Footprint within agreed zone.'),
      it: sectionReview('Approved', 'Cabin location confirmed clear.'),
      welfare: sectionReview(
        'Approved',
        'Welfare capacity within compound limits.'
      ),
      workforce: sectionReview(
        'Approved',
        'Headcount plan is within site limits.'
      ),
    },
  },
  {
    id: 'SRF-0033',
    srfNumber: '0033',
    dateRaised: '11/06/2025',
    teamcenterNumber: '101555142',
    revision: '001',
    title: 'Temporary IT Cabin Installation',
    originatorCompanyName: 'Kier',
    projectContractRefNumber: 'ADW000-076',
    mobilisationDate: '15/09/2025',
    demobilisationDate: '30/06/2026',
    plotFootprint: 'Cabin footprint 10mx6m = 60 M2',
    developmentSiteType: 'OSI',
    mainDevelopmentSiteArea: 'N/A (OSI)',
    siteZone: 'N/A (OSI)',
    requestTypeMds: 'N/A (OSI)',
    laydownWarehousePort: 'Port of Lowestoft',
    areaOsi: 'Compound B',
    requestTypeOsi: 'IT & Power',
    status: 'Draft',
    modules: {
      workArea: false,
      it: true,
      water: false,
      welfare: false,
      power: true,
      workforce: false,
    },
    workforceData: NO_WORKFORCE_DATA,
    sectionReviews: {},
  },
  {
    id: 'SRF-0034',
    srfNumber: '0034',
    dateRaised: '20/06/2025',
    teamcenterNumber: '101555188',
    revision: '003',
    title: 'Laydown Area Power Upgrade',
    originatorCompanyName: 'Morgan Sindall',
    projectContractRefNumber: 'ADW000-055',
    mobilisationDate: '28/09/2025',
    demobilisationDate: '31/03/2027',
    plotFootprint: 'Laydown area 80mx80m = 6,400 M2',
    developmentSiteType: 'MDS',
    mainDevelopmentSiteArea: '(TCA) West',
    siteZone: 'Zone 8',
    requestTypeMds: 'Work Area & Power',
    laydownWarehousePort: 'N/A (MDS)',
    areaOsi: 'N/A (MDS)',
    requestTypeOsi: 'N/A (MDS)',
    status: 'Submitted',
    modules: {
      workArea: true,
      it: false,
      water: false,
      welfare: false,
      power: true,
      workforce: true,
    },
    workforceData: {
      counts: {
        '2025-09': 50,
        '2025-10': 50,
        '2025-11': 50,
        '2025-12': 50,
        '2026-01': 50,
        '2026-02': 50,
        '2026-03': 70,
        '2026-04': 70,
        '2026-05': 70,
        '2026-06': 70,
        '2026-07': 70,
        '2026-08': 70,
        '2026-09': 70,
        '2026-10': 70,
        '2026-11': 85,
        '2026-12': 85,
        '2027-01': 85,
        '2027-02': 85,
        '2027-03': 85,
      },
    },
    sectionReviews: {
      general: sectionReview('Under Review'),
      'work-area': sectionReview('Under Review'),
      power: sectionReview('Under Review'),
      workforce: sectionReview('Under Review'),
    },
  },
  {
    id: 'SRF-0035',
    srfNumber: '0035',
    dateRaised: '02/07/2025',
    teamcenterNumber: '101555221',
    revision: '001',
    title: 'Port Warehouse Water Connection',
    originatorCompanyName: 'Clancy',
    projectContractRefNumber: 'ADW000-042',
    mobilisationDate: '10/10/2025',
    demobilisationDate: '28/02/2026',
    plotFootprint: 'Warehouse plot 25mx15m = 375 M2',
    developmentSiteType: 'OSI',
    mainDevelopmentSiteArea: 'N/A (OSI)',
    siteZone: 'N/A (OSI)',
    requestTypeMds: 'N/A (OSI)',
    laydownWarehousePort: 'Port of Lowestoft',
    areaOsi: 'Warehouse 4',
    requestTypeOsi: 'Water',
    status: 'Rejected',
    modules: {
      workArea: false,
      it: false,
      water: true,
      welfare: false,
      power: false,
      workforce: false,
    },
    workforceData: NO_WORKFORCE_DATA,
    sectionReviews: {
      general: sectionReview(
        'Rejected',
        'Requested compound overlaps an existing marine licence exclusion zone. Please resubmit with a revised footprint.'
      ),
      water: sectionReview(
        'Rejected',
        'Connection point conflicts with the exclusion zone — see General comment.'
      ),
    },
  },
];

export default SPACE_REQUEST_MOCK_DATA;
