import type { ReviewRecord } from './reviewerTypes';
import type { WorkforceMonthData } from '../SpaceRequestForm/spaceRequestFormTypes';

const NO_WORKFORCE_DATA: WorkforceMonthData = {
  counts: {},
};

export const REVIEWER_MOCK_DATA: ReviewRecord[] = [
  {
    id: 'REV-2041',
    srfNumber: '2041',
    dateRaised: '14/07/2025',
    teamcenterNumber: '101556310',
    revision: '001',
    title: 'Turbine Hall Access Road Widening',
    originatorCompanyName: 'Costain',
    projectContractRefNumber: 'ADW000-091',
    mobilisationDate: '05/09/2025',
    demobilisationDate: '20/02/2026',
    plotFootprint: 'Access road widening 300mx8m = 2,400 M2',
    developmentSiteType: 'MDS',
    mainDevelopmentSiteArea: '(TCA) North',
    siteZone: 'Zone 5',
    requestTypeMds: 'Work Area & Power',
    laydownWarehousePort: 'N/A (MDS)',
    areaOsi: 'N/A (MDS)',
    requestTypeOsi: 'N/A (MDS)',
    status: 'Submitted',
    modules: {
      workArea: true,
      it: false,
      water: false,
      welfare: false,
      power: true,
      workforce: true,
    },
    workforceData: {
      counts: {
        '2025-09': 25,
        '2025-10': 25,
        '2025-11': 30,
        '2025-12': 30,
        '2026-01': 30,
        '2026-02': 30,
      },
    },
    reviewComment: '',
  },
  {
    id: 'REV-2042',
    srfNumber: '2042',
    dateRaised: '18/07/2025',
    teamcenterNumber: '101556377',
    revision: '002',
    title: 'Contractor Welfare Village Extension',
    originatorCompanyName: 'Laing O’Rourke',
    projectContractRefNumber: 'ADW000-104',
    mobilisationDate: '10/09/2025',
    demobilisationDate: '30/11/2026',
    plotFootprint: 'Village extension 70mx40m = 2,800 M2',
    developmentSiteType: 'MDS',
    mainDevelopmentSiteArea: '(TCA) East',
    siteZone: 'Zone 3',
    requestTypeMds: 'Welfare & Water',
    laydownWarehousePort: 'N/A (MDS)',
    areaOsi: 'N/A (MDS)',
    requestTypeOsi: 'N/A (MDS)',
    status: 'Approved',
    modules: {
      workArea: false,
      it: false,
      water: true,
      welfare: true,
      power: false,
      workforce: false,
    },
    workforceData: NO_WORKFORCE_DATA,
    reviewComment:
      'Layout and welfare capacity match the site plan on file. Approved as submitted.',
  },
  {
    id: 'REV-2043',
    srfNumber: '2043',
    dateRaised: '22/07/2025',
    teamcenterNumber: '101556412',
    revision: '001',
    title: 'Marine Works Site Office Cabin',
    originatorCompanyName: 'Van Oord',
    projectContractRefNumber: 'ADW000-063',
    mobilisationDate: '01/10/2025',
    demobilisationDate: '31/08/2026',
    plotFootprint: 'Cabin footprint 12mx8m = 96 M2',
    developmentSiteType: 'OSI',
    mainDevelopmentSiteArea: 'N/A (OSI)',
    siteZone: 'N/A (OSI)',
    requestTypeMds: 'N/A (OSI)',
    laydownWarehousePort: 'Port of Lowestoft',
    areaOsi: 'Compound C',
    requestTypeOsi: 'IT & Power',
    status: 'Rejected',
    modules: {
      workArea: false,
      it: true,
      water: false,
      welfare: false,
      power: true,
      workforce: false,
    },
    workforceData: NO_WORKFORCE_DATA,
    reviewComment:
      'Requested compound overlaps an existing marine licence exclusion zone. Please resubmit with a revised footprint.',
  },
  {
    id: 'REV-2044',
    srfNumber: '2044',
    dateRaised: '29/07/2025',
    teamcenterNumber: '101556488',
    revision: '001',
    title: 'Substation Laydown & Workforce Ramp-Up',
    originatorCompanyName: 'Balfour Beatty',
    projectContractRefNumber: 'ADW000-118',
    mobilisationDate: '12/10/2025',
    demobilisationDate: '15/06/2027',
    plotFootprint: 'Laydown area 90mx60m = 5,400 M2',
    developmentSiteType: 'MDS',
    mainDevelopmentSiteArea: '(TCA) West',
    siteZone: 'Zone 8',
    requestTypeMds: 'Work Area & Workforce',
    laydownWarehousePort: 'N/A (MDS)',
    areaOsi: 'N/A (MDS)',
    requestTypeOsi: 'N/A (MDS)',
    status: 'Submitted',
    modules: {
      workArea: true,
      it: true,
      water: false,
      welfare: true,
      power: true,
      workforce: true,
    },
    workforceData: {
      counts: {
        '2025-10': 45,
        '2025-11': 45,
        '2025-12': 60,
        '2026-01': 60,
        '2026-02': 60,
        '2026-03': 80,
        '2026-04': 80,
      },
    },
    reviewComment: '',
  },
];

export default REVIEWER_MOCK_DATA;
