import { OrgUser } from './userManagementTypes';

export const MOCK_USERS: OrgUser[] = [
  {
    id: 'u1',
    firstName: 'Olivia',
    lastName: 'Bennett',
    email: 'olivia.bennett@sizewell.co.uk',
    phone: '+44 7700 900111',
    role: 'Role 1',
    company: 'Sizewell C',
    lastLogin: '2026-07-06T14:49:00',
  },
  {
    id: 'u2',
    firstName: 'Ethan',
    lastName: 'Wallace',
    email: 'ethan.wallace@sizewell.co.uk',
    phone: '+44 7700 900112',
    role: 'Role 2',
    company: 'Sizewell C',
    lastLogin: null,
  },
  {
    id: 'u3',
    firstName: 'Grace',
    lastName: 'Turner',
    email: 'grace.turner@sizewell.co.uk',
    phone: '+44 7700 900113',
    role: 'Role 3',
    company: 'Bylor JV',
    lastLogin: '2026-07-03T10:54:00',
  },
  {
    id: 'u4',
    firstName: 'Daniel',
    lastName: 'Foster',
    email: 'daniel.foster@sizewell.co.uk',
    phone: '+44 7700 900114',
    role: 'Role 1',
    company: 'Altrad Services',
    lastLogin: '2026-06-24T09:27:00',
  },
  {
    id: 'u5',
    firstName: 'Sophie',
    lastName: 'Clarke',
    email: 'sophie.clarke@sizewell.co.uk',
    phone: '+44 7700 900115',
    role: 'Role 2',
    company: 'Sizewell C',
    lastLogin: null,
  },
  {
    id: 'u6',
    firstName: 'Liam',
    lastName: 'Anderson',
    email: 'liam.anderson@sizewell.co.uk',
    phone: '+44 7700 900116',
    role: 'Role 3',
    company: 'Sizewell C',
    lastLogin: '2026-06-20T08:15:00',
  },
  {
    id: 'u7',
    firstName: 'Ruby',
    lastName: 'Matthews',
    email: 'ruby.matthews@sizewell.co.uk',
    phone: '+44 7700 900117',
    role: 'Role 1',
    company: 'Bylor JV',
    lastLogin: null,
  },
  {
    id: 'u8',
    firstName: 'Noah',
    lastName: 'Richardson',
    email: 'noah.richardson@sizewell.co.uk',
    phone: '+44 7700 900118',
    role: 'Role 2',
    company: 'Altrad Services',
    lastLogin: '2026-06-18T13:32:00',
  },
];
